apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: file-retain-storage-ext4
  namespace: gxfs-idsa
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
