---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omejdn-proxy
  labels:
    app: omejdn-proxy-app
  namespace: gxfs-idsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omejdn-proxy-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omejdn-proxy-app
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: omejdn-proxy
          image: nginx:1.21.6
          envFrom:
            - configMapRef:
                name: omejdn-proxy-env-config
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: omejdn-conf
      volumes:
        - name: omejdn-conf
          configMap:
            name: omejdn-proxy-data-config
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omejdn-server
  labels:
    app: omejdn-server-app
  namespace: gxfs-idsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omejdn-server-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omejdn-server-app
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      initContainers:
        - name: omejdn-server-init
          image: busybox:1.34.1
          command: ['sh', '-c', '/tmp/init/init.sh']
          volumeMounts:
            - mountPath: /opt/config
              name: config-dir
            - mountPath: /opt/keys
              name: keys-dir
            - mountPath: /tmp/init
              name: config-init-file
            - mountPath: /tmp/init/config
              name: config-files
            - mountPath: /tmp/init/keys
              name: config-key-files
      containers:
        - name: omejdn-server
          image: ghcr.io/fraunhofer-aisec/omejdn-server:1.6.0
          ports:
            - containerPort: 4567
          envFrom:
            - configMapRef:
                name: omejdn-server-env-config
          volumeMounts:
            - mountPath: /opt/config/
              name: config-dir
            - mountPath: /opt/keys/
              name: keys-dir
      volumes:
        - name: config-dir
          emptyDir: {}
        - name: keys-dir
          emptyDir: {}
        - name: config-init-file
          configMap:
            name: omejdn-server-init-config
            defaultMode: 0777
        - name: config-files
          configMap:
            name: omejdn-server-data-config
        - name: config-key-files
          configMap:
            name: omejdn-server-key-data-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omejdn-ui
  labels:
    app: omejdn-ui-app
  namespace: gxfs-idsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omejdn-ui-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omejdn-ui-app
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: omejdn-ui
          image: ghcr.io/fraunhofer-aisec/omejdn-ui:dev
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: omejdn-ui-config
      restartPolicy: Always
