---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsa-omejdn
  labels:
    app: omejdn-app
  namespace: gxfs-idsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omejdn-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omejdn-app
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: omejdn
          image: nginx:1.21.6
          envFrom:
            - configMapRef:
                name: omejdn-config
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/templates/default.conf.template
              name: omejdn
      volumes:
        - name: omejdn
          configMap:
            name: omejdn-config
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsa-omejdn-server
  labels:
    app: omejdn-server-app
  namespace: gxfs-idsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omejdn-server-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omejdn-server-app
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      initContainers:
        - name: omejdn-server-init
          image: busybox:1.34.1
          command: ['sh', '-c', 'cp /tmp/config/* /opt/config/']
          volumeMounts:
            - mountPath: /tmp/config
              name: config-files
            - mountPath: /opt/config
              name: config-dir
      containers:
        - name: omejdn-server
          image: ghcr.io/fraunhofer-aisec/omejdn-server:1.6.0
          envFrom:
            - configMapRef:
                name: omejdn-server-env
          volumeMounts:
            - mountPath: /opt/keys/
              name: keys-files
      volumes:
        - name: config-dir
          emptyDir: {}
        - name: config-files
          configMap:
            name: omejdn-server-config
        - name: keys-files
          configMap:
            name: omejdn-server-keys

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idsa-omejdn-ui
  labels:
    app: omejdn-ui-app
  namespace: gxfs-idsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omejdn-ui-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omejdn-ui-app
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: omejdn-ui
          image: ghcr.io/fraunhofer-aisec/omejdn-ui:dev
          envFrom:
            - configMapRef:
                name: omejdn-ui-config
      restartPolicy: Always