apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-pv
  namespace: gxfs-idsa
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"