kind: PersistentVolume
apiVersion: v1
metadata:
  name: broker-mongodb-pv
  namespace: gxfs-idsa
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db