apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-core-config-env
  namespace: gxfs-idsa
data:
  SPARQL_URL: "http://broker-fuseki-service:3030/connectorData"
  ELASTICSEARCH_HOSTNAME: "broker-elasticsearch-service"
  SHACL_VALIDATION: "true"
  DAPS_VALIDATE_INCOMING: "false"
  COMPONENT_URI: "https://www.gxfs.gx4fm.org/idsa-broker-api"
  COMPONENT_CATALOGURI: "https://www.gxfs.gx4fm.org/idsa-broker-api/connectors/"
  DAPS_URL: "http://daps-proxy-service/auth/token"
  IDENTITY_JAVAKEYSTORE: "/etc/cert/isstbroker-keystore.jks"
  JWKS_TRUSTEDHOSTS: "daps-proxy-service"
  JAVA_HOME: "/opt/java/openjdk/"
