apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-fuseki-pvc
  namespace: gxfs-idsa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: file-retain-storage-ext4
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-elasticsearch-pvc
  namespace: gxfs-idsa
spec:
  # TODO: elasticsearch crashes with ReadWriteMany access mode! fix it
  accessModes:
     - ReadWriteOnce
  storageClassName: file-retain-storage-ext4
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-mongodb-pvc
  namespace: gxfs-idsa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: file-retain-storage-xfs
  resources:
    requests:
      storage: 1Gi
