apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-fuseki-pvc
  namespace: gxfs-idsa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: file-retain-storage
  resources:
    requests:
      storage: 1Gi
