apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: file-retain-storage
  namespace: gxfs-idsa
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
parameters:
  skuName: Standard_LRS
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
volumeBindingMode: Immediate
